### ISSUE TITLE
looks like jsonb conversion in  #328 broke passing `undefined` in triggers

### ISSUE THREAD

**Issue by pkit** [plv8/plv8js#353] opened 2019-07-26 16:06 UTC
very hard to reproduce in isolation but the flow is as following:

- have a table with a jsonb column
- attach trigger to the table "before insert for each row"
- rewrite the jsonb column in the trigger by using `Object.assign()`
- use some `undefined` values in the assignment like this: 
`Object.assign({}, NEW, { key: undefined })`

what happens:

- the following log items are produced: `NOTICE:  Unaccounted for type: Undefined`
- the resulting jsonb will include: `{ key: "undefined" }` instead of the empty key or null

**Comment by JerrySievert** [comment] 2019-07-26 16:19
to be fair, `undefined` is not a valid value in JSON, so technically this is just as valid as alternatives :)

I can reject `undefined`, by ignoring it "silently" (with a `NOTICE`)

**Comment by pkit** [comment] 2019-07-26 17:18
It was working before `3.0alpha` :)
In all other places `undefined` is silently cast to `NULL` IIRC

**Comment by JerrySievert** [comment] 2019-07-26 17:52
and by "working" you mean one specific undefined behavior of `undefined` that did what you wanted it to, as opposed to another specific undefined behavior of `undefined` that doesn't do what you want it to :)

I can make the change to set it to `null`, that's pretty straightforward.  I'll see about an update either today or tomorrow, and back port to the 2.3 branch.

**Comment by pkit** [comment] 2019-07-26 17:56
too leaky :)
either all are cast to null or none
otherwise it's C++ all over again!!

**Comment by JerrySievert** [comment] 2019-07-26 17:58
well, it's just as simple to ignore an `undefined`. and don't remind me to much about c++, that's what I'm doing in another window at the moment.

**Comment by JerrySievert** [comment] 2019-08-13 16:12
do you have a simple test case for this in the form of a simple stored procedure?  I'd like to add the simplest tests to the regressions.

looks like checking for `->IsNull()` and `->IsUndefined()` both and setting null should fix it.

**Comment by pkit** [comment] 2019-08-13 17:07
Yep, I can assemble a test case for it.
Probably later today.

**Comment by JerrySievert** [comment] 2019-08-13 17:08
thanks much!  I'm taking care of as many open issues as I can in one go.

**Comment by pkit** [comment] 2019-08-13 17:35
```
create or replace function jsonb_undefined(data jsonb) returns jsonb as
$v8$
  return Object.assign({}, data, { key: undefined });
$v8$
language plv8
;
select jsonb_undefined('{"a": 1}'::jsonb);
```
stringified output:
```
[{"jsonb_undefined":{"a":1,"key":"undefined"}}]
```

**Comment by pkit** [comment] 2019-08-13 17:37
oops, it looks like there is another problem here.. `"0":{"a":1}` or I'm not interpreting this correctly?

**Comment by JerrySievert** [comment] 2019-08-13 17:47
jsonb has no concept of `undefined` so likely the best I can do is set it to `null`.

**Comment by pkit** [comment] 2019-08-13 17:49
Yep, null is cool. But if we compare with json
```
create or replace function json_undefined(data json) returns json as
$v8$
  return Object.assign({}, data, { key: undefined });
$v8$
language plv8
;
select json_undefined('{"a": 1}'::json);
```
output
```
[{"json_undefined":{"a":1}}]
```

**Comment by JerrySievert** [comment] 2019-08-13 17:51
yeah, I tested the `json` version as well.   I can look at a short-circuit in the conversion code, I'm just wary of too many branches in the code.

**Comment by JerrySievert** [comment] 2019-08-13 17:55
looks like I'm safely discarding the results anyways, I think it can be done without additional regressions.

**Comment by JerrySievert** [comment] 2019-08-13 20:51
live on 3.0alpha and back ported to 2.3.13 - closing.

**Closed as completed by JerrySievert** 2019-08-13 20:51 UTC
